### ISSUE TITLE
"Select all"-checkbox in multi-select

### ISSUE THREAD

**Issue by LetschM** [UB-Mannheim/ocr-gt-tools#31] opened 2016-04-26 11:38 UTC
Could be useful in some cases, for example if almost every line on a page is italic. You would just have to click on the "select all" button, perhaps unselect the one or two non-italic lines and click on the "italic"-button to comment on every selected line once.

**Comment by kba** [comment] 2016-04-26 11:53
Duplicate of #30

**Closed as completed by kba** 2016-04-26 11:53 UTC
Labels: invalid
